#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Revisar siempre xrandr -q y colocar segun aparezca el nombre de su monitor, puede veriar con un guion
internal_monitor=eDP1
external_monitor=HDMI1

monitor_add() {
	desktops=4 # How many desktops to move to the second monitor

	for desktop in $(bspc query -D -m $internal_monitor | sed "$desktops"q)
  do
		bspc desktop $desktop --to-monitor $external_monitor
  done

  # Remove "Desktop" created by bspwm
  bspc desktop Desktop --remove
}

monitor_remove() {
	bspc monitor $internal_monitor -a Desktop # Temp desktop because one desktop required per monitor

	# Move everything to external monitor to reorder desktops
	for desktop in $(bspc query -D -m $internal_monitor)
	do
		bspc desktop $desktop --to-monitor $external_monitor
	done

	# Now move everything back to internal monitor
	bspc monitor $external_monitor -a Desktop # Temp desktop

	for desktop in $(bspc query -D -m $external_monitor)
	do
		bspc desktop $desktop --to-monitor $internal_monitor
	done

	bspc desktop Desktop --remove # Remove temp desktops
}

if [[ $(xrandr -q | grep "$external_monitor connected") ]]; then
    monitor_add
    xrandr --output eDP1 --primary --mode 1366x768 --pos 0x312 --rotate normal --output HDMI1 --mode 1920x1080 --pos 1366x0 --rotate normal --output VIRTUAL1 --off
		#xrandr --output eDP-1 --primary --mode 1366x768 --pos 0x312 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 1366x0 --rotate normal
		bspc monitor eDP1 -d I II III
		bspc monitor HDMI1 -d IV V VI VII VIII
else
		monitor_remove
		bspc monitor -d I II III IV V VII
fi

#bspc monitor -d I II III IV V VII
#bspc monitor HDMI1 -d I II III IV V VII

bspc config border_width 3
bspc config focused_border_color \#D2A63B
bspc config normal_border_color \#D2D8E0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 25
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

# Autostart
$HOME/.screenlayout/screen.sh &
setxkbmap -option grp:alt_shift_toggle latam,'us(intl)',us &
nitrogen --restore &
picom &
compton --restore &
xsetroot -cursor_name left_ptr &
xrdb ${HOME}/.Xresources
${HOME}/.config/polybar/launch.sh &
